import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Provider } from "./provider";
import Providers from "./Providers";
import { cn } from "@/lib/utils";
import AuthProvider from "@/components/auth-provider";
import AuthProviderWrapper from "@/components/auth-provider.wrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              <AuthProviderWrapper>{children}</AuthProviderWrapper>
            </Providers>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
